name: Run npm start

# Define when the workflow should trigger
on:
  push:
    branches:
      - main   # Only run on pushes to the main branch
  pull_request:
    branches:
      - main   # Also run on pull requests to main branch

# Define the jobs in the workflow
jobs:
  start-npm:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use Node.js version 16 (or specify a different version as needed)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run "npm start"
      - name: Run npm start
        run: npm start
